### ISSUE TITLE
Getting error due to unhandled catch block

### ISSUE THREAD

**Issue by avicoder** [codeflixde/csi-red-alert#1]
```
$ node /app/main.js -f "$CI_PROJECT_DIR/gl-repository-scanning-report.json" -e $ENVIRONMENT -c sourceCode -i $CI_PROJECT_PATH
(node:42) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:42) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:42) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Yaml file:
```
variables:
  ENVIRONMENT: $CI_COMMIT_REF_SLUG
  ISSUE_ACCESS_TOKEN: $CI_ISSUE_TOKEN
  SLACK_TOKEN: $SLACK

image:
    name: codeflixde/csi-red-alert:latest
run:
  script:
    - trivy --version
    # update vulnerabilities db
    - time trivy --download-db-only --no-progress --cache-dir .trivycache/
    # Builds report and puts it in the default workdir $CI_PROJECT_DIR, so `artifacts:` can take it from there
    - time trivy filesystem --exit-code 0 --no-progress --format template --template "@/contrib/gitlab.tpl"
      --output "$CI_PROJECT_DIR/gl-repository-scanning-report.json" ./
    # Prints full report
    - time trivy filesystem --exit-code 0 --no-progress ./
    # Notify about fixable vulnerabilities
    - node /app/main.js -f "$CI_PROJECT_DIR/gl-repository-scanning-report.json" -e $ENVIRONMENT -c sourceCode -i $CI_PROJECT_PATH
    # Fails on high and critical vulnerabilities
    - time trivy filesystem --exit-code 1 --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL --no-progress ./
```
